_core:
  default_config_hash: TghDxAeHu4gER0JZhzPbMawpRgxggVsIu54oyTeaJOo
load_all_enabled_fonts: 1
enabled_fonts:
  - 'https://www.google.com/webfonts/family?family=Roboto Slab&subset=cyrillic#100'
  - 'https://www.google.com/webfonts/family?family=Roboto Slab&subset=latin#100'
load_on_themes: {  }
